version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5002:5000"
    volumes:
      - ./backend:/app
  frontend:
    build: ./frontend
    ports:
      - "3002:3000"
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
